version: '2'
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: ../dockerfiles/Dockerfile.frontend
    container_name: 'cds.ai-fullstack-frontend'
    volumes: 
      - ./frontend:/app
      - /app/node_modules/
    ports:
      - 5173:5173
    command: npm run dev -- --host
  
  backend:
    build:
      context: ./backend/
      dockerfile: ../dockerfiles/Dockerfile.backend
    container_name: 'cds.ai-fullstack-backend'
    volumes:
    - ./backend:/code/app
    ports:
      - 8000:8000
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000